// GENERATED by scripts/gen-tokens.mjs from docs/design-handoff/02-design-tokens/tokens.json — do not edit.
/* eslint-disable */

export const palette = {
  "light": {
    "surface": "#f9e3dc",
    "gradPeach": "#f9d7c3",
    "gradPink": "#f1b6cf",
    "gradLilac": "#d3aaec",
    "glass": "rgba(255,255,255,0.55)",
    "glassStrong": "rgba(255,255,255,0.80)",
    "glassEdge": "rgba(255,255,255,0.75)",
    "surfaceRaised": "#fff7f5",
    "surfaceSunken": "#f3dde6",
    "track": "rgba(59,35,66,0.12)",
    "line": "#ecd3dd",
    "lineStrong": "#c3aac2",
    "ink": "#33203a",
    "inkMuted": "#553f5d",
    "primary": "#2a1d2e",
    "onPrimary": "#ffffff",
    "peach": "#ec9275",
    "accent": "#7a3dae",
    "onAccent": "#ffffff",
    "primarySoft": "#fbdfea",
    "accentSoft": "#eee0fa",
    "wave": "#ffffff",
    "record": "#c93a57",
    "onRecord": "#ffffff",
    "success": "#1f6c61",
    "successSoft": "#d9efe8",
    "warning": "#8a4f00",
    "warningSoft": "#fcebd3",
    "keyWhite": "#ffffff",
    "keyBlack": "#33203a",
    "focusRing": "{accent}",
    "note": "{accent}"
  },
  "dark": {
    "surface": "#1a1320",
    "gradPeach": "#3b2230",
    "gradPink": "#3d1f3d",
    "gradLilac": "#2b1f4a",
    "glass": "rgba(44,30,54,0.62)",
    "glassStrong": "rgba(48,33,60,0.86)",
    "glassEdge": "rgba(255,255,255,0.12)",
    "surfaceRaised": "#271d2f",
    "surfaceSunken": "#140f19",
    "track": "rgba(255,255,255,0.16)",
    "line": "#3b2d45",
    "lineStrong": "#8a7396",
    "ink": "#f8ecf4",
    "inkMuted": "#c7b4cf",
    "primary": "#f8ecf4",
    "onPrimary": "#2a1d2e",
    "peach": "#f4a88c",
    "accent": "#d2b4ff",
    "onAccent": "#22163f",
    "primarySoft": "#4a2440",
    "accentSoft": "#3a2a60",
    "wave": "#f6d9ec",
    "record": "#ff8aa2",
    "onRecord": "#3a0710",
    "success": "#6fd0bf",
    "successSoft": "#173a34",
    "warning": "#f3b562",
    "warningSoft": "#3f2d12",
    "keyWhite": "#efe6ee",
    "keyBlack": "#0d0a10",
    "focusRing": "{accent}",
    "note": "{accent}"
  }
} as const;

export type ColorName = keyof typeof palette.light;
export type Palette = { [K in ColorName]: string };

export const typeScale = {
  "largeTitle": {
    "fontSize": 34,
    "lineHeight": 38,
    "fontWeight": 600,
    "letterSpacing": -1.02
  },
  "hero": {
    "fontSize": 44,
    "lineHeight": 46,
    "fontWeight": 600,
    "letterSpacing": -1.76
  },
  "title2": {
    "fontSize": 24,
    "lineHeight": 28,
    "fontWeight": 600,
    "letterSpacing": -0.48
  },
  "numeral": {
    "fontSize": 44,
    "lineHeight": 48,
    "fontWeight": 500,
    "letterSpacing": -0.88
  },
  "eyebrow": {
    "fontSize": 13,
    "lineHeight": 16,
    "fontWeight": 500,
    "letterSpacing": 1.82
  },
  "headline": {
    "fontSize": 17,
    "lineHeight": 22,
    "fontWeight": 600,
    "letterSpacing": 0
  },
  "body": {
    "fontSize": 17,
    "lineHeight": 24,
    "fontWeight": 400,
    "letterSpacing": 0
  },
  "callout": {
    "fontSize": 15,
    "lineHeight": 20,
    "fontWeight": 400,
    "letterSpacing": 0
  },
  "footnote": {
    "fontSize": 13,
    "lineHeight": 18,
    "fontWeight": 400,
    "letterSpacing": 0
  },
  "caption": {
    "fontSize": 12,
    "lineHeight": 16,
    "fontWeight": 600,
    "letterSpacing": 0.72
  }
} as const;

export type TypeVariant = keyof typeof typeScale;

export const space = {"1":4,"2":8,"3":12,"4":16,"5":24,"6":32} as const;
export const radius = {"sm":10,"md":16,"lg":28,"pill":999} as const;
export interface Shadow { shadowColor: string; shadowOffset: { width: number; height: number }; shadowRadius: number; shadowOpacity: number }
export const shadows: Record<'light' | 'dark', Record<'card' | 'disc' | 'knob', Shadow>> = {
  "light": {
    "card": {
      "shadowColor": "rgb(131,71,120)",
      "shadowOffset": {
        "width": 0,
        "height": 12
      },
      "shadowRadius": 16,
      "shadowOpacity": 0.14
    },
    "disc": {
      "shadowColor": "rgb(42,29,46)",
      "shadowOffset": {
        "width": 0,
        "height": 10
      },
      "shadowRadius": 14,
      "shadowOpacity": 0.35
    },
    "knob": {
      "shadowColor": "rgb(51,32,58)",
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 4,
      "shadowOpacity": 0.25
    }
  },
  "dark": {
    "card": {
      "shadowColor": "rgb(0,0,0)",
      "shadowOffset": {
        "width": 0,
        "height": 12
      },
      "shadowRadius": 16,
      "shadowOpacity": 0.45
    },
    "disc": {
      "shadowColor": "rgb(0,0,0)",
      "shadowOffset": {
        "width": 0,
        "height": 10
      },
      "shadowRadius": 14,
      "shadowOpacity": 0.55
    },
    "knob": {
      "shadowColor": "rgb(0,0,0)",
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 4,
      "shadowOpacity": 0.5
    }
  }
};
export const blurGlass = 24;
