import type { RawNotes, ScoreSettings } from '@aria/score-engine';

/**
 * Curated scores for public-domain pieces (generated by scripts/curated/build-curated.mjs from Mutopia
 * Project sources — see scripts/curated/SOURCES.md). Keyed by seed-catalog id; each file loads on first use.
 */
interface CuratedFile {
  title: string;
  composer: string;
  source: string;
  license: string;
  credit?: string;
  settings: ScoreSettings & { tempoBpm: number };
  /** [pitch, start, length (quarter beats from bar 1), velocity, staff 0 = treble / 1 = bass] */
  notes: [number, number, number, number, 0 | 1][];
}

/* eslint-disable @typescript-eslint/no-require-imports */
const FILES: Record<string, () => CuratedFile> = {
  'fu-r-elise--beethoven': () => require('./fu-r-elise--beethoven.json'),
  'gymnope-die-no-1--satie': () => require('./gymnope-die-no-1--satie.json'),
  'clair-de-lune--debussy': () => require('./clair-de-lune--debussy.json'),
  'prelude-in-e-minor-op-28-no-4--chopin': () => require('./prelude-in-e-minor-op-28-no-4--chopin.json'),
  'minuet-in-g--bach-attr-petzold': () => require('./minuet-in-g--bach-attr-petzold.json'),
  'moonlight-sonata-1st-mvt--beethoven': () => require('./moonlight-sonata-1st-mvt--beethoven.json'),
  'arabesque-no-1--debussy': () => require('./arabesque-no-1--debussy.json'),
  'nocturne-in-e-flat-op-9-no-2--chopin': () => require('./nocturne-in-e-flat-op-9-no-2--chopin.json'),
  'maple-leaf-rag--scott-joplin': () => require('./maple-leaf-rag--scott-joplin.json'),
  'the-entertainer--scott-joplin': () => require('./the-entertainer--scott-joplin.json'),
  'amazing-grace--traditional': () => require('./amazing-grace--traditional.json'),
};

export const hasCuratedScore = (catalogId: string | undefined): catalogId is string => !!catalogId && catalogId in FILES;

export interface CuratedScore {
  raw: RawNotes;
  settings: ScoreSettings;
  /** "Public Domain · Mutopia Project" / "CC BY-SA 3.0 · Typeset by … · Mutopia Project" */
  attribution: string;
}

const cache = new Map<string, CuratedScore>();

export function loadCuratedScore(catalogId: string): CuratedScore | null {
  const hit = cache.get(catalogId);
  if (hit) return hit;
  const load = FILES[catalogId];
  if (!load) return null;
  const f = load();
  const spb = 60 / f.settings.tempoBpm; // seconds per quarter beat
  const raw: RawNotes = {
    notes: f.notes.map(([pitch, start, len, velocity, staff], i) => ({
      id: `c${i + 1}`,
      pitch,
      onset: start * spb,
      offset: (start + len) * spb,
      velocity,
      staff: staff === 0 ? 'treble' : 'bass',
    })),
    pedal: [],
    exactTempoBpm: f.settings.tempoBpm,
  };
  const attribution = [f.license, f.credit, 'Mutopia Project'].filter(Boolean).join(' · ');
  const score = { raw, settings: f.settings, attribution };
  cache.set(catalogId, score);
  return score;
}
