// Generates src/theme/tokens.generated.ts from the design system's tokens.json.
// Usage: node scripts/gen-tokens.mjs [--check]   (--check fails if the output is stale)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'docs/design-handoff/02-design-tokens/tokens.json');
const out = join(root, 'src/theme/tokens.generated.ts');
const tokens = JSON.parse(readFileSync(src, 'utf8'));

const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const px = (v) => Number(String(v).replace('px', ''));
const em = (v, size) => Math.round(Number(String(v).replace('em', '')) * size * 100) / 100;

function parseShadow(v) {
  // "0 12px 32px rgba(131,71,120,0.14)" -> RN shadow props (iOS)
  const m = v.match(/^(-?\d+)(?:px)? (-?\d+)(?:px)? (\d+)(?:px)? rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)$/);
  if (!m) throw new Error(`Unparsed shadow: ${v}`);
  const [, x, y, blur, r, g, b, a] = m;
  return {
    shadowColor: `rgb(${r},${g},${b})`,
    shadowOffset: { width: Number(x), height: Number(y) },
    shadowRadius: Number(blur) / 2,
    shadowOpacity: Number(a),
  };
}

const light = {};
const dark = {};
for (const t of tokens.color.tokens) {
  const name = camel(t.name);
  const resolve = (v) => (typeof v === 'string' && v.startsWith('var(') ? null : v);
  light[name] = resolve(t.value.light) ?? t.value.light;
  dark[name] = resolve(t.value.dark) ?? t.value.dark;
}
// Resolve aliases like var(--accent)
for (const pal of [light, dark]) {
  for (const [k, v] of Object.entries(pal)) {
    const m = typeof v === 'string' && v.match(/^var\(--([a-z0-9-]+)\)$/);
    if (m) pal[k] = pal[camel(m[1])];
  }
}

const type = {};
for (const group of tokens.type.groups) {
  for (const s of group.styles) {
    const size = px(s.fontSize);
    type[camel(s.name)] = {
      fontSize: size,
      lineHeight: px(s.lineHeight),
      fontWeight: s.fontWeight,
      letterSpacing: s.letterSpacing ? em(s.letterSpacing, size) : 0,
      ...(s.textTransform ? { textTransform: s.textTransform } : {}),
    };
  }
}

const space = Object.fromEntries(tokens.spacing.tokens.map((t) => [Number(t.name.split('-')[1]), px(t.value)]));
const radius = Object.fromEntries(tokens.radius.tokens.map((t) => [camel(t.name.replace('radius-', '')), px(t.value)]));
const shadow = {
  light: Object.fromEntries(tokens.shadow.tokens.map((t) => [camel(t.name.replace('shadow-', '')), parseShadow(t.value.light)])),
  dark: Object.fromEntries(tokens.shadow.tokens.map((t) => [camel(t.name.replace('shadow-', '')), parseShadow(t.value.dark)])),
};
const blur = px(tokens.blur.tokens[0].value);

const body = `// GENERATED by scripts/gen-tokens.mjs from docs/design-handoff/02-design-tokens/tokens.json — do not edit.
/* eslint-disable */

export const palette = ${JSON.stringify({ light, dark }, null, 2)} as const;

export type ColorName = keyof typeof palette.light;
export type Palette = { [K in ColorName]: string };

export const typeScale = ${JSON.stringify(type, null, 2)} as const;

export type TypeVariant = keyof typeof typeScale;

export const space = ${JSON.stringify(space)} as const;
export const radius = ${JSON.stringify(radius)} as const;
export interface Shadow { shadowColor: string; shadowOffset: { width: number; height: number }; shadowRadius: number; shadowOpacity: number }
export const shadows: Record<'light' | 'dark', Record<${Object.keys(shadow.light).map(k=>`'${k}'`).join(' | ')}, Shadow>> = ${JSON.stringify(shadow, null, 2)};
export const blurGlass = ${blur};
`;

if (process.argv.includes('--check')) {
  if (!existsSync(out) || readFileSync(out, 'utf8') !== body) {
    console.error('tokens.generated.ts is stale — run `pnpm gen:tokens`.');
    process.exit(1);
  }
  console.log('tokens up to date');
} else {
  writeFileSync(out, body);
  console.log(`wrote ${out}`);
}
