// Generates src/ui/icons.generated.ts: path data for the Phosphor icons Aria uses (05-icons/ICONS.md),
// in the three weights the design system allows. Source: @phosphor-icons/core (MIT).
// Usage: node scripts/gen-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const assets = join(root, 'node_modules/@phosphor-icons/core/assets');

// design name → phosphor name (ICONS.md), plus lock/hourglass for Keyboard mode states.
const MAP = {
  play: 'play', pause: 'pause', next: 'skip-forward', back: 'clock-counter-clockwise',
  'chevron-left': 'caret-left', 'chevron-right': 'caret-right', heart: 'heart', timer: 'timer',
  repeat: 'repeat', shuffle: 'shuffle', mic: 'microphone', record: 'record', sliders: 'sliders-horizontal',
  metronome: 'metronome', speed: 'gauge', note: 'music-note', check: 'check', close: 'x', plus: 'plus',
  discover: 'sparkle', learning: 'music-notes', library: 'books', alert: 'warning', wave: 'waveform',
  search: 'magnifying-glass', piano: 'piano-keys', headphones: 'headphones', share: 'share-network',
  star: 'star', settings: 'gear-six', more: 'dots-three', sort: 'sort-ascending', export: 'export',
  trash: 'trash', pencil: 'pencil-simple', undo: 'arrow-u-up-left', minus: 'minus', redo: 'arrow-u-up-right',
  up: 'caret-up', down: 'caret-down', file: 'file-text', cloud: 'cloud-arrow-up', import: 'download-simple',
  hourglass: 'hourglass', stop: 'stop', 'play-circle': 'play-circle',
};

const out = {};
for (const [name, ph] of Object.entries(MAP)) {
  out[name] = {};
  for (const weight of ['duotone', 'fill', 'bold']) {
    const svg = readFileSync(join(assets, weight, `${ph}-${weight}.svg`), 'utf8');
    // Keep path d + whether it's the 20% tint layer; drop the 256 bounding rect Phosphor includes.
    const paths = [...svg.matchAll(/<path d="([^"]+)"( opacity="0\.2")?\s*\/>/g)].map((m) => [m[1], m[2] ? 1 : 0]);
    if (!paths.length) throw new Error(`no paths in ${ph}-${weight}`);
    out[name][weight] = paths;
  }
}

writeFileSync(
  join(root, 'src/ui/icons.generated.ts'),
  `// GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (MIT) — do not edit.\n` +
    `// Each path: [d, isTintLayer]. viewBox 0 0 256 256.\n` +
    `export type IconPaths = ReadonlyArray<readonly [string, 0 | 1]>;\n` +
    `export const ICON_PATHS = ${JSON.stringify(out)} as const satisfies Record<string, Record<'duotone' | 'fill' | 'bold', IconPaths>>;\n`,
);
console.log(`wrote ${Object.keys(out).length} icons`);
